[build]
  command = "npm install && npm run build"
  publish = "build"

[build.environment]
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  REACT_APP_API_BASE_URL = "https://scmsnew-production.up.railway.app/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 